services:
  postgres:
    image: postgres:16
    container_name: ai_genie_pg
    environment:
      POSTGRES_USER: aigenie
      POSTGRES_PASSWORD: aigenie_pass
      POSTGRES_DB: aigenie_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
